#!/usr/bin/env python
"""Stage 7 -- leave-one-out moderator ablations, Supplementary Figures S1-S4.

These were the answer to Reviewer 1's central objection in Revision 2 -- that
the HMM's contribution within the unified model was never demonstrated -- and
the response letter reports numbers taken from them. Yet no stage produced
them: the tables sat in `results/` from the Revision 2 commit, referenced by no
document and regenerated by nothing, which is the same failure mode the main
figures had.

Each supplementary figure compares the full five-moderator model against the
model with one annotation removed:

    S1  without HMM constraint          MINUS_log_constraint
    S2  without GERP RS                 MINUS_GERP_RS
    S3  without AM pathogenicity        MINUS_log_pathogenicity
    S4  without pLoF and missense       NO_pLoF_NO_missense

Two further single-moderator ablations, MINUS_pLoF_ind and MINUS_missense_ind,
have no figure of their own but are needed for the dominant-moderator
attribution the response letter quotes, so they are fitted too.

On gating. The published panels went through Word and survive only as 1299x1092
images inside `Supplemental Data.pdf`, so they cannot be pixel-compared. The
tables can: `jobs/gate_07_ablations.sbatch` asserts bit-identity against the six
committed MINUS_*/NO_* files. The figures are then rendered from gated numbers,
and this stage prints the annotated gene set for each panel so it can be read
against the published ones.

  python pipelines/07_moderator_ablations.py --as-published   # gate
  python pipelines/07_moderator_ablations.py                  # corrected
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from wgs_constraint import (  # noqa: E402
    MODERATORS, fit_per_gene, get_config, prepare_regression_input,
)

# (published filename stem, moderators dropped, figure, human label)
ABLATIONS = [
    ("MINUS_log_constraint", ["log_constraint"], "S1", "HMM constraint"),
    ("MINUS_GERP_RS", ["GERP_RS"], "S2", "GERP RS"),
    ("MINUS_log_pathogenicity", ["log_pathogenicity"], "S3", "AM pathogenicity"),
    ("NO_pLoF_NO_missense", ["pLoF_ind", "missense_ind"], "S4",
     "pLoF/missense annotations"),
    ("MINUS_pLoF_ind", ["pLoF_ind"], None, "pLoF annotation"),
    ("MINUS_missense_ind", ["missense_ind"], None, "missense annotation"),
]

GROUP_ORDER = ["DEE", "EPI", "GGE", "NAFE"]
ANNOTATE_MIN_DELTA = 1.0     # caption: absolute log10(p) difference exceeds 1
ANNOTATE_MIN_MLOG = 6.0      # caption: at least one model achieves p < 1e-6
NBINS = 10


def log(message):
    print(message, flush=True)


def render(full, without, label, figure, cfg, suffix):
    """One supplementary panel set: two by two over the epilepsy groups.

    Matches the published layout -- x is the ablated model, y is the full one,
    a red dashed diagonal marks equivalence, and a shared colourbar carries
    log-scaled counts.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm

    merged = full.merge(without, on=["gene_id", "gene_name", "group"],
                        suffixes=("_full", "_without"))
    for col in ("p_unified_full", "p_unified_without"):
        merged[col] = pd.to_numeric(merged[col], errors="coerce")
    merged = merged[(merged["p_unified_full"] > 0)
                    & (merged["p_unified_without"] > 0)].copy()
    # .to_numpy(dtype=float) rather than relying on the pd.to_numeric above.
    # scipy's f.sf returns a 0-d array for some models, so fit_per_gene's
    # p_unified arrives as an object column, and np.log10 over objects raises
    # rather than vectorising. Stage 11 hit the same thing.
    merged["y"] = -np.log10(merged["p_unified_full"].to_numpy(dtype=float))
    merged["x"] = -np.log10(merged["p_unified_without"].to_numpy(dtype=float))
    merged.replace([np.inf, -np.inf], np.nan, inplace=True)
    merged = merged.dropna(subset=["x", "y"])

    top = float(max(merged["x"].max(), merged["y"].max()))
    edges = np.linspace(0, top, NBINS + 1)

    fig, axes = plt.subplots(2, 2, figsize=(11, 9.5), sharex=True, sharey=True)
    fig.suptitle("Unified model p-values: with vs without " + label,
                 fontsize=14, fontweight="bold")
    annotated = {}
    mesh = None
    for ax, group in zip(axes.flat, GROUP_ORDER):
        sub = merged[merged["group"] == group]
        if sub.empty:
            ax.set_visible(False)
            continue
        _, _, _, mesh = ax.hist2d(sub["x"], sub["y"], bins=[edges, edges],
                                  cmap="Blues", norm=LogNorm())
        ax.plot([0, top], [0, top], color="red", linestyle="--", linewidth=1)
        ax.text(0.97, 0.04, "Group: " + group, transform=ax.transAxes,
                ha="right", va="bottom", fontsize=11, fontweight="bold")

        hit = sub[(np.abs(sub["y"] - sub["x"]) > ANNOTATE_MIN_DELTA)
                  & (sub[["x", "y"]].max(axis=1) > ANNOTATE_MIN_MLOG)]
        annotated[group] = sorted(hit["gene_name"].dropna().astype(str))
        for _, row in hit.iterrows():
            ax.text(row["x"], row["y"], str(row["gene_name"]), fontsize=6,
                    ha="center", va="bottom")

    fig.supxlabel("$-\\log_{10}(p)$ without " + label, fontsize=12)
    fig.supylabel("$-\\log_{10}(p)$ full model", fontsize=12)
    if mesh is not None:
        fig.colorbar(mesh, ax=axes, label="Log-scaled count", shrink=0.85)
    out = cfg.result("Figure " + figure + ": unified model with vs without "
                     + label + suffix + ".png")
    fig.savefig(out, dpi=300)
    plt.close(fig)
    log("      " + out.name)
    return annotated


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--as-published", action="store_true",
                        help="fit from the pre-correction regression input")
    parser.add_argument("--no-figures", action="store_true")
    args = parser.parse_args()

    cfg = get_config()
    suffix = "_REPRO" if args.as_published else "_FIXED"
    log(cfg.describe())
    log("input suffix: " + suffix + "\n")

    src = cfg.result("constraint_gerp_am_epi25_variants" + suffix + ".tsv.gz")
    log("[1/3] loading " + src.name + " ...")
    prepared = prepare_regression_input(
        pd.read_csv(src, sep="\t"), clip_epsilon=cfg.param("clip_epsilon"))
    log(f"      {len(prepared):,} variant rows")

    log("[2/3] fitting the full model and six ablations ...")
    full = fit_per_gene(prepared)
    log(f"      full ({len(MODERATORS)} moderators): {len(full):,} models")
    fits = {}
    for stem, dropped, _, label in ABLATIONS:
        keep = [m for m in MODERATORS if m not in dropped]
        fit = fit_per_gene(prepared, moderators=keep)
        fits[stem] = fit
        out = cfg.result("epilepsy_unified_model_pvalues_" + stem + suffix
                         + ".tsv")
        fit.to_csv(out, sep="\t", index=False)
        log(f"      minus {label:<26} {len(fit):,} models -> {out.name}")

    log("[3/3] figures and attribution ...")
    if not args.no_figures:
        for stem, _, figure, label in ABLATIONS:
            if figure is None:
                continue
            annotated = render(full, fits[stem], label, figure, cfg, suffix)
            for group, names in annotated.items():
                if names:
                    log("        " + figure + " " + group + ": "
                        + ", ".join(names))

    # The response letter attributes each significant gene-group to the
    # moderator whose removal costs it the most signal.
    threshold = cfg.param("exome_wide_threshold")
    full_p = pd.to_numeric(full["p_unified"], errors="coerce")
    sig = full[full_p < threshold].copy()
    singles = [(stem, label) for stem, dropped, _, label in ABLATIONS
               if len(dropped) == 1]
    for stem, _ in singles:
        joined = sig.merge(fits[stem][["gene_id", "group", "p_unified"]],
                           on=["gene_id", "group"], suffixes=("", "_abl"))
        without = pd.to_numeric(joined["p_unified_abl"], errors="coerce")
        base = pd.to_numeric(joined["p_unified"], errors="coerce")
        sig[stem] = (np.log10(without.to_numpy(dtype=float))
                     - np.log10(base.to_numpy(dtype=float)))
    cols = [stem for stem, _ in singles]
    sig["dominant"] = sig[cols].idxmax(axis=1)
    table = cfg.result("moderator_attribution" + suffix + ".tsv")
    sig.to_csv(table, sep="\t", index=False)

    label_of = {stem: label for stem, _, _, label in ABLATIONS}
    print()
    print("=" * 66)
    print("MODERATOR ABLATIONS [" + suffix.lstrip("_") + "]")
    print("=" * 66)
    print(f"  gene-groups fitted            : {len(full):,}")
    print(f"  exome-wide significant (full) : {len(sig)}")
    print("  dominant moderator among them:")
    for stem, count in sig["dominant"].value_counts().items():
        print(f"    {label_of[stem]:<26} {count:>3}")
    print("  -> " + table.name)
    print("=" * 66)


if __name__ == "__main__":
    main()
