#!/usr/bin/env python
"""Stage 7 -- leave-one-out moderator ablations, Supplementary Figures S1-S4.

These answered Reviewer 1's central objection in Revision 2 -- that the HMM's
contribution inside the unified model was never demonstrated -- and the response
letter quotes numbers taken from them. Yet no stage produced them: the tables
sat in `results/` from the Revision 2 commit, referenced by no document and
regenerated by nothing, which is the failure mode the main figures had.

Extracted from `Epilepsy Analysis.ipynb` cell 35 (rendering) and the fits that
feed it. Each supplementary figure compares the full five-moderator model
against the model with one annotation removed:

    S1  without HMM constraint          MINUS_log_constraint
    S2  without GERP RS                 MINUS_GERP_RS
    S3  without AM pathogenicity        MINUS_log_pathogenicity
    S4  without pLoF and missense       NO_pLoF_NO_missense

Two further single-moderator ablations, MINUS_pLoF_ind and MINUS_missense_ind,
have no supplementary figure but are needed for the dominant-moderator
attribution the response letter quotes, so their tables are fitted too.

Three details of cell 35 that are easy to miss and change the figure:

  * **Both** models are filtered to ``n_variants >= 25`` before plotting. An
    earlier version of this stage plotted all 72,386 gene-groups and annotated
    sixteen genes in the S1 DEE panel where the published one has seven; the
    extras were all below the inclusion floor.
  * p is clipped to a floor of 1e-300 before taking logs, so a gene-group with
    p == 0 lands at 300 rather than at infinity.
  * The axis limit is the global maximum **plus one**, and the same limit sets
    both the bin edges and the group-label position.

  python pipelines/07_moderator_ablations.py --as-published   # gate
  python pipelines/07_moderator_ablations.py                  # corrected
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from wgs_constraint import (  # noqa: E402
    MODERATORS, fit_per_gene, get_config, prepare_regression_input,
)

KEY_COLS = ["gene_id", "gene_name", "group"]
NUM_BINS = 10
P_THRESHOLD = 1e-6        # cell 35: annotate if either model beats this
DELTA_THRESHOLD = 1       # cell 35: ... and the log10 gap is at least this
ANNOT_FONTSIZE = 6
EPS = 1e-300
FIGSIZE = (12, 10)

# (table stem, moderators dropped, supplementary figure, title, x label,
#  published png stem)
ABLATIONS = [
    ("MINUS_log_constraint", ["log_constraint"], "S1",
     "Unified Model p-values: with vs without HMM Constraint",
     r"$-log_{10}(p)$ without HMM constraint",
     "Figure_heatmap_FULL_vs_MINUS_log_constraint_2x2"),
    ("MINUS_GERP_RS", ["GERP_RS"], "S2",
     "Unified Model p-values: with vs without GERP RS score",
     r"$-log_{10}(p)$ without GERP RS",
     "Figure_heatmap_FULL_vs_MINUS_GERP_RS_2x2"),
    ("MINUS_log_pathogenicity", ["log_pathogenicity"], "S3",
     "Unified Model p-values: with vs without AM Pathogenicity",
     r"$-log_{10}(p)$ without AM pathogenicity",
     "Figure_heatmap_FULL_vs_MINUS_log_pathogenicity_2x2"),
    ("NO_pLoF_NO_missense", ["pLoF_ind", "missense_ind"], "S4",
     "Unified Model p-values: with vs without pLoF/Missense Annotations",
     r"$-log_{10}(p)$ without pLoF/missense",
     "Figure_heatmap_FULL_vs_ALT_no_pLoF_no_missense_2x2"),
    # No supplementary figure; fitted for the attribution only. Exploratory
    # 2x2 PNGs for these two do exist in results/, but cell 35's comparison
    # list does not define their titles, so they are not regenerated here
    # rather than guessed at and gated against a guess.
    ("MINUS_pLoF_ind", ["pLoF_ind"], None, None, None, None),
    ("MINUS_missense_ind", ["missense_ind"], None, None, None, None),
]


def log(message):
    print(message, flush=True)


def make_cmp(full, other, min_variants):
    """Cell 35's make_cmp: join, apply the floor to both, take clipped logs."""
    other = other.copy()
    other["p_unified"] = pd.to_numeric(other["p_unified"], errors="coerce")

    cmp = (
        full[KEY_COLS + ["n_variants", "p_unified"]]
        .rename(columns={"n_variants": "n_with", "p_unified": "p_with"})
        .merge(
            other[KEY_COLS + ["n_variants", "p_unified"]]
            .rename(columns={"n_variants": "n_without", "p_unified": "p_without"}),
            on=KEY_COLS, how="inner",
        )
    )
    cmp = cmp[(cmp["n_with"] >= min_variants)
              & (cmp["n_without"] >= min_variants)].copy()
    cmp["p_with"] = pd.to_numeric(cmp["p_with"], errors="coerce")
    cmp["p_without"] = pd.to_numeric(cmp["p_without"], errors="coerce")
    cmp = cmp.dropna(subset=["p_with", "p_without"]).reset_index(drop=True)

    cmp["log10_with"] = -np.log10(
        np.clip(cmp["p_with"].to_numpy(dtype=float), EPS, 1.0))
    cmp["log10_without"] = -np.log10(
        np.clip(cmp["p_without"].to_numpy(dtype=float), EPS, 1.0))
    cmp["delta"] = cmp["log10_with"] - cmp["log10_without"]
    return cmp


def render(cmp, title, x_label, out_path):
    """Cell 35's plot_heatmap_grid_no_gap, preserved including its manual axes.

    The 2x2 grid is positioned by hand so the panels touch, and the colourbar
    is a fifth axes to the right. `tight_layout` would move everything.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm

    groups = sorted(cmp["group"].dropna().unique())
    if len(groups) != 4:
        log(f"      warning: expected 4 groups, found {len(groups)}: {groups}")

    global_max = max(cmp["log10_with"].max(), cmp["log10_without"].max())
    if not np.isfinite(global_max):
        global_max = 1
    limit = global_max + 1
    x_edges = np.linspace(0, limit, NUM_BINS + 1)
    y_edges = np.linspace(0, limit, NUM_BINS + 1)

    fig = plt.figure(figsize=FIGSIZE)
    left, right = 0.08, 0.88
    bottom, top = 0.08, 0.92
    width, height = (right - left), (top - bottom)
    side = min(width / 2, height / 2)
    grid_l = left + (width - 2 * side) / 2
    grid_b = bottom + (height - 2 * side) / 2
    positions = {
        0: [grid_l + 0 * side, grid_b + 1 * side, side, side],
        1: [grid_l + 1 * side, grid_b + 1 * side, side, side],
        2: [grid_l + 0 * side, grid_b + 0 * side, side, side],
        3: [grid_l + 1 * side, grid_b + 0 * side, side, side],
    }
    axes = [fig.add_axes(positions[i]) for i in range(4)]
    mappable = None
    annotated = {}

    for ax, group in zip(axes, groups):
        df = cmp[cmp["group"] == group].copy()
        hist = ax.hist2d(df["log10_without"], df["log10_with"],
                         bins=[x_edges, y_edges], cmap="Blues", norm=LogNorm())
        mappable = hist[3]
        ax.plot([0, limit], [0, limit], linestyle="--", color="red",
                linewidth=1.0, alpha=0.6)

        annot = df[((df["p_with"] < P_THRESHOLD) | (df["p_without"] < P_THRESHOLD))
                   & (np.abs(df["delta"]) >= DELTA_THRESHOLD)].copy()
        annotated[group] = sorted(annot["gene_name"].dropna().astype(str))
        for _, row in annot.iterrows():
            ax.text(row["log10_without"], row["log10_with"], row["gene_name"],
                    fontsize=ANNOT_FONTSIZE, ha="center", va="center")

        ax.set_xlim(0, limit)
        ax.set_ylim(0, limit)
        ax.text(0.97 * limit, 0.03 * limit, f"Group: {group}", fontsize=12,
                fontweight="bold", ha="right", va="bottom")

    axes[0].set_xticklabels([])
    axes[1].set_xticklabels([])
    axes[1].set_yticklabels([])
    axes[3].set_yticklabels([])

    fig.suptitle(title, fontsize=16, fontweight="bold", y=0.97)
    fig.supxlabel(x_label, fontsize=14)
    fig.supylabel(r"$-log_{10}(p)$ full model", fontsize=14)

    cbar_ax = fig.add_axes([0.91, grid_b, 0.02, 2 * side])
    fig.colorbar(mappable, cax=cbar_ax).set_label("Log-scaled count")

    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    log(f"      {Path(out_path).name}")
    return annotated


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--as-published", action="store_true",
                        help="fit from the pre-correction regression input")
    parser.add_argument("--no-figures", action="store_true")
    args = parser.parse_args()

    cfg = get_config()
    suffix = "_REPRO" if args.as_published else "_FIXED"
    min_variants = cfg.param("min_variants")
    log(cfg.describe())
    log(f"input suffix: {suffix}\n")

    src = cfg.result(f"constraint_gerp_am_epi25_variants{suffix}.tsv.gz")
    log(f"[1/3] loading {src.name} ...")
    prepared = prepare_regression_input(
        pd.read_csv(src, sep="\t"), clip_epsilon=cfg.param("clip_epsilon"))
    log(f"      {len(prepared):,} variant rows")

    log("[2/3] fitting the full model and six ablations ...")
    full = fit_per_gene(prepared)
    full["p_unified"] = pd.to_numeric(full["p_unified"], errors="coerce")
    log(f"      full ({len(MODERATORS)} moderators): {len(full):,} models")

    fits = {}
    for stem, dropped, _, _, _, _ in ABLATIONS:
        keep = [m for m in MODERATORS if m not in dropped]
        fit = fit_per_gene(prepared, moderators=keep)
        fits[stem] = fit
        out = cfg.result(f"epilepsy_unified_model_pvalues_{stem}{suffix}.tsv")
        fit.to_csv(out, sep="\t", index=False)
        log(f"      minus {', '.join(dropped):<28} {len(fit):,} -> {out.name}")

    log("[3/3] figures and attribution ...")
    if not args.no_figures:
        for stem, _, figure, title, x_label, png in ABLATIONS:
            if figure is None:
                continue
            cmp = make_cmp(full, fits[stem], min_variants)
            log(f"      {figure}: {len(cmp):,} gene-groups above the "
                f"n>={min_variants} floor")
            annotated = render(cmp, title, x_label,
                               cfg.result(f"{png}{suffix}.png"))
            for group, names in annotated.items():
                if names:
                    log(f"        {figure} {group}: {', '.join(names)}")

    # Dominant-moderator attribution.
    #
    # The response letter states: "Across the 33 gene-group pairs reaching
    # exome-wide significance under the unified model, the dominant moderator is
    # the predicted loss-of-function term for 13, predicted pathogenicity for 7,
    # the missense annotation for 5, HMM-derived constraint for 5, and GERP RS
    # for 3."
    #
    # "Dominant" means the moderator with the smallest **coefficient** p-value
    # in the full model -- not, as looks natural, the one whose removal costs the
    # most signal. Those give different answers: on the ablation reading pLoF is
    # dominant for 3 gene-groups, on the coefficient reading for 13. The
    # coefficient reading over the merged table reproduces all five counts and
    # the total exactly, so that is what the letter did.
    #
    # The population is the merged Epi25/G4E table at n_variants >= 25, not the
    # raw p-value table: the raw table gives 35 pairs and 13/8/6/5/3, because it
    # includes gene-groups with no Epi25 match.
    #
    # Note this needs no ablation at all. The ablations are for the figures.
    coef_columns = {
        "p_pLoF": "pLoF",
        "p_pathogenicity": "pathogenicity",
        "p_missense": "missense",
        "p_constraint": "HMM constraint",
        "p_gerp": "GERP RS",
    }
    merged_path = cfg.result(
        f"unified_epi25_g4e_merged_n{min_variants}{suffix}.tsv.gz")
    if not merged_path.exists():
        merged_path = cfg.result(
            f"unified_epi25_g4e_merged_n{min_variants}.tsv.gz")

    print()
    print("=" * 66)
    print(f"MODERATOR ABLATIONS [{suffix.lstrip('_')}]")
    print("=" * 66)
    print(f"  gene-groups fitted            : {len(full):,}")
    if not merged_path.exists():
        print("  attribution skipped: no merged Epi25/G4E table. Run "
              "pipelines/02 first.")
        print("=" * 66)
        return

    merged = pd.read_csv(merged_path, sep="	")
    for column in list(coef_columns) + ["p_unified", "n_variants"]:
        if column in merged.columns:
            merged[column] = pd.to_numeric(merged[column], errors="coerce")
    merged = merged[merged["n_variants"] >= min_variants]
    sig = merged[merged["p_unified"] < cfg.param("exome_wide_threshold")].copy()
    present = [c for c in coef_columns if c in sig.columns]
    sig["dominant"] = sig[present].idxmin(axis=1)
    table = cfg.result(f"moderator_attribution{suffix}.tsv")
    sig.to_csv(table, sep="	", index=False)

    counts = sig["dominant"].value_counts()
    print(f"  source                        : {merged_path.name}")
    print(f"  exome-wide significant pairs  : {len(sig)}")
    print("  dominant moderator (smallest coefficient p-value):")
    for column, name in coef_columns.items():
        if column in present:
            print(f"    {name:<18} {int(counts.get(column, 0)):>3}")
    print(f"  -> {table.name}")
    print("=" * 66)


if __name__ == "__main__":
    main()
